stages:
- build
- cleanup_build
- test
- cleanup

build_job:
  stage: build
  script:
  - sudo ./builders/buildlocal /opt/COMPSs
  only:
  - trunk

cleanup_build_job:
  stage: cleanup_build
  script:
  - rm -rf /opt/COMPSs
  when: on_failure
  only:
  - trunk

test_job:
  stage: test
  script:
  - ./tests/scripts/main local local.cfg
  only:
  - trunk

cleanup_job:
  stage: cleanup
  script:
  - sudo rm -rf /opt/COMPSs
  - sudo rm -rf ~/.COMPSs
  - sudo rm -rf /home/gitlab-runner/tests*
  when: on_success
  only:
  - trunk
