stages:
- build
- clean
- test
- headers
- cleanup_build

build_job:
  stage: build
  script:
  - mvn install sonar:sonar -Dsonar.host.url=http://bscgrid05.bsc.es/sonar/
  - sudo ./builders/buildlocal /opt/COMPSs
  only: 
  - triggers

cleanup_failure:
  stage: clean
  script:
  - sudo rm -rf /opt/COMPSs
  - sudo rm -rf /home/gitlab-runner/tests*
  - sudo rm -rf /home/gitlab-runner/.COMPSs
  when: on_failure
  only:
  - triggers

test_job:
  stage: test
  script:
  - 'sudo chown -R gitlab-runner: *'
  - ./tests/scripts/main local local.cfg
  only:
  - triggers

header_setup:
  stage: headers
  script:
  - ./utils/scripts/header_setup/replace_all.sh
  - 'git commit -am "ci: added missing headers"'
  - git push http:${GIT_USER}:{GIT_PASSWD}@compss.bsc.es/gitlab/compss/framework.git ${CI_COMMIT_REF_NAME}
  only:
  - triggers

cleanup_build_job:
  stage: cleanup_build
  script:
  - sudo rm -rf /opt/COMPSs
  - sudo rm -rf /home/gitlab-runner/tests*
  - sudo rm -rf /home/gitlab-runner/.COMPSs
  only:
  - triggers

