stages:
- build
- clean
- test
- cleanup_build

build_job:
  stage: build
  script:
  - mvn install sonar:sonar -Dsonar.host.url=http://bscgrid05.bsc.es/sonar/
  - sudo ./builders/buildlocal /opt/COMPSs
  only: 
  - triggers

cleanup_failure:
  stage: clean
  script:
  - sudo rm -rf /opt/COMPSs
  - sudo rm -rf /home/gitlab-runner/tests*
  - sudo rm -rf /home/gitlab-runner/.COMPSs
  when: on_failure
  only:
  - triggers

test_job:
  stage: test
  script:
  #- echo "Disabled tests" #./tests/scripts/main local local.cfg
  - ./tests/scripts/main local local.cfg
  only:
  - triggers


cleanup_build_job:
  stage: cleanup_build
  script:
  - sudo rm -rf /opt/COMPSs
  - sudo rm -rf /home/gitlab-runner/tests*
  - sudo rm -rf /home/gitlab-runner/.COMPSs
  only:
  - triggers
