stages:
- build
- clean
- test
- cleanup_build

build_job:
  stage: build
  script:
  - sudo ./builders/buildlocal /opt/COMPSs
  - sudo chown -R gitlab-runner ./builders/*

cleanup_failure:
  stage: clean
  script:
  - sudo rm -rf /opt/COMPSs
  - sudo rm -rf /home/gitlab-runner/tests*
  - sudo rm -rf /home/gitlab-runner/.COMPSs
  when: on_failure

test_job:
  stage: test
  script:
  - echo "Disabled tests" #./tests/scripts/main local local.cfg


cleanup_build_job:
  stage: cleanup_build
  script:
  - sudo rm -rf /opt/COMPSs
  - sudo rm -rf /home/gitlab-runner/tests*
  - sudo rm -rf /home/gitlab-runner/.COMPSs

